In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.24.3


In [4]:
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [5]:
#dimension of the array
arr1.ndim

1

In [8]:
#shape of array
arr1.shape

(3,)

In [6]:
arr2=np.array([[-3,2,0],[4,9,-7]])
arr2

array([[-3,  2,  0],
       [ 4,  9, -7]])

In [7]:
arr2.ndim

2

In [9]:
arr2.shape

(2, 3)

In [10]:
arr3=np.array([[[-3,2,0],[4,9,-7]]])
arr3

array([[[-3,  2,  0],
        [ 4,  9, -7]]])

In [11]:
arr3.shape

(1, 2, 3)

In [12]:
arr3.ndim

3

In [13]:
arr4=np.array([[[2,5,6],[9,5,7],[2,0,1]],[[-2,-5,-6],[-9,-5,-7],[-2,0,-1]]])
arr4

array([[[ 2,  5,  6],
        [ 9,  5,  7],
        [ 2,  0,  1]],

       [[-2, -5, -6],
        [-9, -5, -7],
        [-2,  0, -1]]])

In [14]:
arr4.ndim

3

In [15]:
arr4.shape

(2, 3, 3)

In [16]:
arr5=np.array([[[-2,0,4],[5,6,3],[9,2,4]],[[-3,-4,5],[-3,2,6]]])
arr5

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
#error becuse the shape of matrixisnot same

In [18]:
arr5=np.array([[1,2,3,4,5,6]])
arr5.shape

(1, 6)

In [24]:
arr6=np.array([[[1,2,3,4,5,6]]])
arr6.shape

(1, 1, 6)

In [25]:
arr7=np.array([[1],[2],[3],[4],[5],[6]])
arr7.shape

(6, 1)

In [3]:
arr8=np.array(range(1,7))
print(arr8)
arr9=np.arange(1,7)
arr9

[1 2 3 4 5 6]


array([1, 2, 3, 4, 5, 6])

In [6]:
arr8=np.array(range(3,37,3))
print(arr8)
arr9=np.arange(3,37,3)
arr9


[ 3  6  9 12 15 18 21 24 27 30 33 36]


array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36])

In [13]:
#shape(1,2,6)
arr9=np.array([[[3,6,9,12,15,18],[21,24,27,30,33,36]]])
arr9.shape
#arr9.ndim

(1, 2, 6)

In [8]:
#shape(1,6,2)
arr9=np.array([[[3,6],[9,12],[15,18],[21,24],[27,30],[33,36]]])
arr9.shape


(1, 6, 2)

In [9]:
#reshape
array10=arr8.reshape(2,2,3)
array10.shape
array10

array([[[ 3,  6,  9],
        [12, 15, 18]],

       [[21, 24, 27],
        [30, 33, 36]]])

In [33]:
arr10=arr8.reshape(2,3,2)
arr10.shape

(2, 3, 2)

In [37]:
#find element in the array
arr10.size

12

In [38]:
#find data type
arr10.dtype

dtype('int64')

In [39]:
arr11=np.array([1.2,1,3,1.4,2.6,3.7])
arr11.dtype

dtype('float64')

In [16]:
#create an array with float data type
#arr12=np.array([1,5,6],dtype=float)
#print(arr12.dtype)
#print(arr12.nbytes)
arr12=np.array([1,2,3,4,5],dtype=np.float32)
arr12.dtype

dtype('float32')

In [42]:
arr12=np.array([1,5,6],dtype=np.float32)
arr12.dtype

dtype('float32')

In [ ]:
arr12=np.array([1,5,6],dtype=np.float16)
arr12.dtype

In [ ]:
arr12=np.array([1,5,6],dtype=np.int16)
arr12.dtype

In [ ]:
arr12=np.array([1,5,6],dtype=np.int8)
arr12.dtype

In [53]:
arr13=np.array([1,5,6,7,8],dtype=np.float64)
print(arr13.dtype)
print(arr13.nbytes)

float64
40


In [58]:
arr14=np.array([range(1,13)]).reshape(2,2,3)
arr14

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [64]:
#read elemet 9
arr14[1][0][2]

9

In [66]:
#read11
arr14[1][1][1]

11

In [67]:
#read  6
arr14[0][1][2]

6

In [ ]:
#read4
#read2

In [17]:
arr15=np.array(range(2,11,2))
print(arr15)
arr15.reshape(5,1)

[ 2  4  6  8 10]


array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]])

In [70]:
arr15.reshape(5,1)

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]])

In [89]:
arr15=np.array(range(2,11,2)).reshape(5,1)
print(arr15)


[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]]


In [88]:
#zero array
np.zeros(3)

array([0., 0., 0.])

In [74]:
np.zeros((2,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [75]:
#allone allay
np.ones(4)

array([1., 1., 1., 1.])

In [76]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [77]:
np.ones((5,4),dtype=np.int8)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [21]:
np.ones((5,4),dtype=np.int8)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int8)

In [79]:
#full array
np.full((3),5)

array([5, 5, 5])

In [80]:
np.full((3,4),0.986)

array([[0.986, 0.986, 0.986, 0.986],
       [0.986, 0.986, 0.986, 0.986],
       [0.986, 0.986, 0.986, 0.986]])

In [81]:
np.full((5,3,4),0.986)

array([[[0.986, 0.986, 0.986, 0.986],
        [0.986, 0.986, 0.986, 0.986],
        [0.986, 0.986, 0.986, 0.986]],

       [[0.986, 0.986, 0.986, 0.986],
        [0.986, 0.986, 0.986, 0.986],
        [0.986, 0.986, 0.986, 0.986]],

       [[0.986, 0.986, 0.986, 0.986],
        [0.986, 0.986, 0.986, 0.986],
        [0.986, 0.986, 0.986, 0.986]],

       [[0.986, 0.986, 0.986, 0.986],
        [0.986, 0.986, 0.986, 0.986],
        [0.986, 0.986, 0.986, 0.986]],

       [[0.986, 0.986, 0.986, 0.986],
        [0.986, 0.986, 0.986, 0.986],
        [0.986, 0.986, 0.986, 0.986]]])

In [83]:
#Line Space
#it will create equalinterval value
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [84]:
np.linspace(0,10,14)

array([ 0.        ,  0.76923077,  1.53846154,  2.30769231,  3.07692308,
        3.84615385,  4.61538462,  5.38461538,  6.15384615,  6.92307692,
        7.69230769,  8.46153846,  9.23076923, 10.        ])

In [85]:
np.linspace(40,100,6)

array([ 40.,  52.,  64.,  76.,  88., 100.])

In [86]:
np.linspace(40,100,6).reshape(3,2,1)

array([[[ 40.],
        [ 52.]],

       [[ 64.],
        [ 76.]],

       [[ 88.],
        [100.]]])

In [90]:
#identity metrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [91]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [2]:
np_array1=np.arange(100)
np_array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
arr2=np.arange(100,dtype=np.float16)
arr2

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.], dtype=float16)

In [6]:
import time
test=100000

list1=range(test)
list2=range(test)

start=time.time()
res=[x+y for x,y in zip(list1,list2)]
stop=time.time()
time_taken=stop-start
print(time_taken*1000)

15.652179718017578


In [8]:
import time
test=100000

arr1=np.arange(test)
arr2=np.arange(test)

start=time.time()
res=arr1+arr2
stop=time.time()
time_taken=stop-start
print(time_taken*1000)

2.3279190063476562


In [ ]:
##shape=dimension of thearray in all axis
#size=total no. of element in the array
#ndim=number of axis/dimension
#

In [12]:
student_marks=np.array([98,76,65,85,90])
print(student_marks)
print(student_marks.ndim)
print(student_marks.size)
print(student_marks.nbytes)
print(student_marks.shape)

[98 76 65 85 90]
1
5
40
(5,)


In [14]:
#student1=np.array([28,100,31,82,35]
#student2=np.array(86,42,25,50,70)
#student3=np.array(89,67,42,73,49)
student=np.array([[28,100,31,82,35],[86,42,25,50,70],[89,67,42,73,49]])
print(student)
print(student.size)
print(student.shape)
print(student.ndim)
print(student.size)


[[ 28 100  31  82  35]
 [ 86  42  25  50  70]
 [ 89  67  42  73  49]]
15
(3, 5)
2
15


In [ ]:
batch70=np.array([40,52,51,60,70],[30,42,35,80,70],[])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
arr1=np.eye(3)
print(arr1)
print(arr1.dtype)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
float64


In [21]:
arr1=np.eye(3,dtype=np.int8)
print(arr1)
print(arr1.dtype)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
int8


In [25]:
arr1=np.diag((2,4,5,6))
print(arr1)

[[2 0 0 0]
 [0 4 0 0]
 [0 0 5 0]
 [0 0 0 6]]


In [26]:
np.diag(np.arange(2,10,2))

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

In [27]:
a=np.ones((3,3),dtype=int)
b=np.diag(np.arange(5,2,-1))
c=a*b
print(c)

[[5 0 0]
 [0 4 0]
 [0 0 3]]


In [29]:
np.linspace(0,30,10)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ])

In [34]:
arr2=np.array([2,5.7,84,72,65.34])
print(arr2)
print(arr2.dtype)
print(arr2.nbytes)
print(arr2.ndim)

[ 2.    5.7  84.   72.   65.34]
float64
40
1


In [36]:
#2darray
arr2=np.array([[2],[5.7],[84],[72],[65.34]])
print(arr2)
print(arr2.dtype)
print(arr2.nbytes)
print(arr2.shape)
print(arr2.ndim)

[[ 2.  ]
 [ 5.7 ]
 [84.  ]
 [72.  ]
 [65.34]]
float64
40
(5, 1)
2


In [35]:
arr2=np.array([2,57,84,72,65])
print(arr2)
print(arr2.dtype)
print(arr2.nbytes)
print(arr2.ndim)

[ 2 57 84 72 65]
int64
40
1


In [22]:
arr3=np.array([45,34,33],dtype=np.int16)
print(arr3)
arr4=np.array([45,31,32],dtype=np.int8)
print(arr4)
arr5=arr3+arr4
print(arr5)
print(arr5.dtype)

[45 34 33]
[45 31 32]
[90 65 65]
int16


In [48]:
arr3=np.array([45,34,33],dtype=np.int16)
print(arr3)
arr4=np.array([45,31,32],dtype=np.int8)
print(arr4)
arr5=np.concatenate((arr3,arr4))
print(arr5)
print(arr5.dtype)

[45 34 33]
[45 31 32]
[45 34 33 45 31 32]
int16


In [52]:
#create some random data
np.random.rand(2,3)

array([[0.66008505, 0.12301417, 0.46870266],
       [0.21758431, 0.55711007, 0.35463947]])

In [53]:
np.random.rand(2,3)

array([[0.55649639, 0.05921536, 0.59291271],
       [0.33542564, 0.00611881, 0.04921399]])

In [35]:
np.random.seed(5)
np.random.rand(2,3)

array([[0.22199317, 0.87073231, 0.20671916],
       [0.91861091, 0.48841119, 0.61174386]])

In [32]:
np.random.randn(2,3)

array([[-1.19276461, -0.20487651, -0.35882895],
       [ 0.6034716 , -1.66478853, -0.70017904]])

In [58]:
np.mean(np.random.rand(23,34))

0.4931531605781546

In [59]:
np.std(np.random.rand(23,34))

0.2820985496691492

In [60]:
np.random.randint(10,size=(3,3))

array([[0, 9, 5],
       [6, 1, 1],
       [8, 3, 3]])

In [37]:
np.random.randint(10,size=(12,12))


array([[4, 2, 2, 1, 2, 3, 1, 2, 4, 9, 0, 1],
       [2, 3, 8, 5, 5, 4, 3, 9, 5, 9, 6, 9],
       [5, 1, 1, 0, 8, 0, 5, 9, 3, 3, 0, 3],
       [7, 3, 7, 3, 2, 6, 6, 2, 7, 0, 3, 7],
       [5, 1, 6, 7, 3, 9, 7, 9, 7, 6, 6, 4],
       [5, 4, 0, 0, 1, 5, 3, 1, 7, 0, 9, 8],
       [3, 4, 4, 9, 9, 6, 7, 9, 6, 0, 7, 1],
       [3, 9, 3, 3, 3, 5, 1, 0, 0, 2, 2, 8],
       [9, 1, 8, 6, 7, 9, 6, 1, 8, 2, 4, 9],
       [5, 9, 1, 8, 6, 1, 5, 1, 8, 8, 8, 3],
       [3, 9, 7, 0, 8, 7, 3, 4, 7, 0, 6, 3],
       [1, 5, 1, 0, 3, 4, 0, 8, 3, 8, 5, 2]])

In [62]:
np.random.randint(45,size=(3,4))

array([[24, 35, 38, 30],
       [14, 23, 21, 31],
       [13,  2,  7, 36]])

In [63]:
np.random.uniform(10,30,size=(3,4))

array([[18.38978617, 26.70412789, 14.94540856, 13.52656226],
       [27.24814256, 27.39790284, 26.85295706, 14.93623264],
       [12.97053648, 15.02761898, 21.63947141, 26.40830791]])

In [64]:
np.random.uniform(0,1,size=(5,5))

array([[0.48461566, 0.78802487, 0.54528602, 0.20846878, 0.48488604],
       [0.27083155, 0.19178414, 0.76580272, 0.46157304, 0.50646054],
       [0.88158973, 0.45822722, 0.54647364, 0.07739488, 0.52549262],
       [0.81537195, 0.9312718 , 0.41066223, 0.11505556, 0.37000561],
       [0.28961098, 0.07190403, 0.3547865 , 0.95828865, 0.85749338]])

In [65]:
a=np.array([[1,2],[3,4]])
b=np.array([[-1,-2],[-3,-4]])
c=a*b
c

array([[ -1,  -4],
       [ -9, -16]])

In [66]:
a=np.array([[1,2],[3,4]])
b=np.array([[-1,-2],[-3,-4]])
c=a@b
c

array([[ -7, -10],
       [-15, -22]])

In [67]:
a=np.random.randint(45,size=(34,34))
b=np.random.randint(78,size=(34,68))
a@b

array([[27000, 32950, 27567, ..., 30162, 33262, 27932],
       [29151, 32056, 32185, ..., 30972, 29275, 27077],
       [27282, 26796, 25612, ..., 26379, 26262, 25822],
       ...,
       [25929, 30463, 27533, ..., 28380, 29445, 25097],
       [33072, 36827, 30816, ..., 36156, 34208, 33549],
       [26085, 30086, 26877, ..., 26269, 24985, 25331]])

In [68]:
a.dot(b)

array([[27000, 32950, 27567, ..., 30162, 33262, 27932],
       [29151, 32056, 32185, ..., 30972, 29275, 27077],
       [27282, 26796, 25612, ..., 26379, 26262, 25822],
       ...,
       [25929, 30463, 27533, ..., 28380, 29445, 25097],
       [33072, 36827, 30816, ..., 36156, 34208, 33549],
       [26085, 30086, 26877, ..., 26269, 24985, 25331]])

In [2]:
d=np.arange(78).reshape(13,2,3)
d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41]],

       [[42, 43, 44],
        [45, 46, 47]],

       [[48, 49, 50],
        [51, 52, 53]],

       [[54, 55, 56],
        [57, 58, 59]],

       [[60, 61, 62],
        [63, 64, 65]],

       [[66, 67, 68],
        [69, 70, 71]],

       [[72, 73, 74],
        [75, 76, 77]]])

In [4]:
#Numpy array Operations
a=np.array([20,30,40])
b=np.array([1,4,6])
c=a+b
print("Addition is",c)
c=a-b
print("Subtraction is",c)

Addition is [21 34 46]
Subtraction is [19 26 34]


In [8]:
arr1=np.arange(72).reshape(2,12,3)
print(arr1)
arr2=-1*np.arange(72).reshape(2,12,3)
print(arr2)
arr3=arr1+arr2
print("Addition is",arr3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]
  [48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]
  [60 61 62]
  [63 64 65]
  [66 67 68]
  [69 70 71]]]
[[[  0  -1  -2]
  [ -3  -4  -5]
  [ -6  -7  -8]
  [ -9 -10 -11]
  [-12 -13 -14]
  [-15 -16 -17]
  [-18 -19 -20]
  [-21 -22 -23]
  [-24 -25 -26]
  [-27 -28 -29]
  [-30 -31 -32]
  [-33 -34 -35]]

 [[-36 -37 -38]
  [-39 -40 -41]
  [-42 -43 -44]
  [-45 -46 -47]
  [-48 -49 -50]
  [-51 -52 -53]
  [-54 -55 -56]
  [-57 -58 -59]
  [-60 -61 -62]
  [-63 -64 -65]
  [-66 -67 -68]
  [-69 -70 -71]]]
Addition is [[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [9]:
b=np.array([1,4,5,6])
c=b**2
c

array([ 1, 16, 25, 36])

In [10]:
d=np.array([[1,2,3],[4,5,6]])
e=d**2
e

array([[ 1,  4,  9],
       [16, 25, 36]])

In [13]:
d=np.arange(8).reshape(2,4)
e=np.array([[45,43,56,78],[2,9,8,7]])
f=d&e
print(f)
g=d|e
print(g)

[[0 1 0 2]
 [0 1 0 7]]
[[45 43 58 79]
 [ 6 13 14  7]]


In [15]:
arr1=np.arange(50,100)
arr1

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [17]:
arr1=np.arange(50,100)
arr1
arr2=arr1.reshape(5,10)
arr2

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [21]:
#print from 50 to 59
print(arr2[0])
print(arr2[0][:10])
print(arr2[:1])

[50 51 52 53 54 55 56 57 58 59]
[50 51 52 53 54 55 56 57 58 59]
[[50 51 52 53 54 55 56 57 58 59]]


In [30]:
#print 1st two rows
print(arr2[:2])
print(arr2[0],arr2[1])
print(arr2[0][:10])
print(arr2[0:2])

[[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]
[50 51 52 53 54 55 56 57 58 59] [60 61 62 63 64 65 66 67 68 69]
[50 51 52 53 54 55 56 57 58 59]
[[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]


In [31]:
print(arr2[0:3:2])

[[50 51 52 53 54 55 56 57 58 59]
 [70 71 72 73 74 75 76 77 78 79]]


In [44]:
#get 1st,2nd and 5th row
print(arr2[[0,1,4]])

[[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [90 91 92 93 94 95 96 97 98 99]]


In [51]:
#find element 53
print(arr2[0][3])
print(arr2[2][7])
print(arr2[4][4])
print(arr2[3,[6,7]])

53
77
94
[86 87]


In [57]:
# 5 dimensional array
arr3=arr2.reshape(1,1,1,25,2)
arr3.ndim

5

In [59]:
#n dimension value is 5
arr3=arr2.reshape(5,5,2)
print(arr3)
arr3.ndim

[[[50 51]
  [52 53]
  [54 55]
  [56 57]
  [58 59]]

 [[60 61]
  [62 63]
  [64 65]
  [66 67]
  [68 69]]

 [[70 71]
  [72 73]
  [74 75]
  [76 77]
  [78 79]]

 [[80 81]
  [82 83]
  [84 85]
  [86 87]
  [88 89]]

 [[90 91]
  [92 93]
  [94 95]
  [96 97]
  [98 99]]]


3

In [78]:
#69
print(arr3[1][4][1])
#59
print(arr3[0][4][1])
#84,85
print(arr3[3][2])
#96,97
print(arr3[4][3])
#50-79
print(arr3[:3])
#50-55
print(arr3[0][:3])
#50,52,54,56,58
print(arr3[0,[0,2,4]])

69
59
[84 85]
[96 97]
[[[50 51]
  [52 53]
  [54 55]
  [56 57]
  [58 59]]

 [[60 61]
  [62 63]
  [64 65]
  [66 67]
  [68 69]]

 [[70 71]
  [72 73]
  [74 75]
  [76 77]
  [78 79]]]
[[50 51]
 [52 53]
 [54 55]]
[[50 51]
 [54 55]
 [58 59]]


In [80]:
print(arr1[9::-1])

[59 58 57 56 55 54 53 52 51 50]


In [81]:
print(arr1[8::-2])

[58 56 54 52 50]


In [82]:
print(arr2[2::-1])

[[70 71 72 73 74 75 76 77 78 79]
 [60 61 62 63 64 65 66 67 68 69]
 [50 51 52 53 54 55 56 57 58 59]]


In [87]:
print(arr1[-41::-1])
print(arr1[-42::-2])
print(arr2[-3::-1])

[59 58 57 56 55 54 53 52 51 50]
[58 56 54 52 50]
[[70 71 72 73 74 75 76 77 78 79]
 [60 61 62 63 64 65 66 67 68 69]
 [50 51 52 53 54 55 56 57 58 59]]


In [88]:
print(arr2[2:5,2:5])

[[72 73 74]
 [82 83 84]
 [92 93 94]]


In [89]:
print(arr2[::-1])

[[90 91 92 93 94 95 96 97 98 99]
 [80 81 82 83 84 85 86 87 88 89]
 [70 71 72 73 74 75 76 77 78 79]
 [60 61 62 63 64 65 66 67 68 69]
 [50 51 52 53 54 55 56 57 58 59]]


In [96]:
print(arr2[:,::-1])

[[59 58 57 56 55 54 53 52 51 50]
 [69 68 67 66 65 64 63 62 61 60]
 [79 78 77 76 75 74 73 72 71 70]
 [89 88 87 86 85 84 83 82 81 80]
 [99 98 97 96 95 94 93 92 91 90]]


In [97]:
print(arr2[::-1,::-1])

[[99 98 97 96 95 94 93 92 91 90]
 [89 88 87 86 85 84 83 82 81 80]
 [79 78 77 76 75 74 73 72 71 70]
 [69 68 67 66 65 64 63 62 61 60]
 [59 58 57 56 55 54 53 52 51 50]]


In [100]:
np.flip(arr2)

array([[99, 98, 97, 96, 95, 94, 93, 92, 91, 90],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50]])

In [101]:
np.flip(arr2,axis=0)

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [102]:
np.flip(arr2,axis=1)

array([[59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [99, 98, 97, 96, 95, 94, 93, 92, 91, 90]])

In [40]:
arr=np.array([[5,9,12,-5,91],[72,6,4,-3,2],[0,-2,56,9,3]])
arr.max(axis=1)

array([91, 72, 56])

In [104]:
arr=np.array([[5,9,12,-5,91],[72,6,4,-3,2],[0,-2,56,9,3]])
arr.sum(axis=1)

array([112,  81,  66])

In [15]:
arr1=np.arange(50,100)
print(arr1)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]


In [16]:
#split into 2 arrays
arr1,arr2=np.split(arr1,2)
print(arr1)
print(arr2)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74]
[75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
 99]


In [30]:
arr=np.arange(50,100)
arr=arr1.reshape(5,10)

In [31]:
#split into 2 arrays in different way
arr1=arr[:, :5]
print(arr1)
print("="*50)
arr2=arr[:,5:]
print(arr2)

[[50 51 52 53 54]
 [60 61 62 63 64]
 [70 71 72 73 74]
 [80 81 82 83 84]
 [90 91 92 93 94]]
[[55 56 57 58 59]
 [65 66 67 68 69]
 [75 76 77 78 79]
 [85 86 87 88 89]
 [95 96 97 98 99]]


In [32]:
#sum of rows such as 50+60+70+80+90
arr1.sum(axis=0)

array([350, 355, 360, 365, 370])

In [33]:
# sumof the element in column such as 50+51+52+53+54
arr1.sum(axis=1)

array([260, 310, 360, 410, 460])

In [34]:
#find maximum Value
arr1.max(axis=0)

array([90, 91, 92, 93, 94])

In [35]:
arr1.max(axis=1)

array([54, 64, 74, 84, 94])

In [36]:
arr1.max()

94

In [37]:
arr1.min()

50

In [38]:
arr1.min(axis=0)

array([50, 51, 52, 53, 54])

In [39]:
arr1.min(axis=1)

array([50, 60, 70, 80, 90])

In [40]:
arr

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [41]:
#mean of the array
arr.mean()

74.5

In [49]:
#finding mean in other way
sum_arr=arr.sum()
print("\n sum of all element in the array is: ",sum_arr)
length=arr.size
print("\n size of the element in array is: ",length)
mean_arr=sum_arr/length
print("\n The man of the Array is: ",mean_arr)


 sum of all element in the array is:  3725

 size of the element in array is:  50

 The man of the Array is:  74.5


In [58]:
# find mean of even number in the array
print(arr[:,::2])
np.mean(arr[:,::2])

[[50 52 54 56 58]
 [60 62 64 66 68]
 [70 72 74 76 78]
 [80 82 84 86 88]
 [90 92 94 96 98]]


74.0

In [56]:
print(arr[:,::1])
np.mean(arr[:,::1])

[[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


74.5

In [57]:
print(arr[:,1::2])
np.mean(arr[:,1::2])

[[51 53 55 57 59]
 [61 63 65 67 69]
 [71 73 75 77 79]
 [81 83 85 87 89]
 [91 93 95 97 99]]


75.0

In [59]:
#findmedian of the array
print(arr[:,::2])
np.median(arr[:,::2])

[[50 52 54 56 58]
 [60 62 64 66 68]
 [70 72 74 76 78]
 [80 82 84 86 88]
 [90 92 94 96 98]]


74.0

In [60]:
print(arr[:,::1])
np.median(arr[:,::1])

[[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


74.5

In [61]:
print(arr[:,1::2])
np.median(arr[:,1::2])

[[51 53 55 57 59]
 [61 63 65 67 69]
 [71 73 75 77 79]
 [81 83 85 87 89]
 [91 93 95 97 99]]


75.0

In [62]:
#variance
variance=np.var(arr)
print("\n The varianace of the array is: ",variance)


 The varianace of the array is:  208.25


In [63]:
#standard deviation
standard_dev=np.std(arr)
print("\n the standard deviation is: ",standard_dev)


 the standard deviation is:  14.430869689661812


In [64]:
#stach operations
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
b=np.arange(1,9).reshape(2,4)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [67]:
c=np.arange(1,7).reshape(3,2)
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [70]:
#to join two arrays
#horizontalstack
Horizontal=np.hstack((a,b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [72]:
Horizontal=np.hstack((a,c))
Horizontal

array([[ 1,  2,  3,  4,  1,  2],
       [ 5,  6,  7,  8,  3,  4],
       [ 9, 10, 11, 12,  5,  6]])

In [74]:
#vertical join
Vertical=np.vstack((a,b))
Vertical

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [75]:
Vertical=np.vstack((a,c))
Vertical

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 2

In [77]:
Vertical=np.vstack((b,c))
Vertical

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 2

In [81]:
#concatenation
np.concatenate((a,c),axis=1)

array([[ 1,  2,  3,  4,  1,  2],
       [ 5,  6,  7,  8,  3,  4],
       [ 9, 10, 11, 12,  5,  6]])

In [84]:
np.hstack((a,c))

array([[ 1,  2,  3,  4,  1,  2],
       [ 5,  6,  7,  8,  3,  4],
       [ 9, 10, 11, 12,  5,  6]])

In [102]:
a=np.array([[1,2,5,3],[2,6,7,8]])
print(a)
b=np.array([[1,5],[4,8],[9,2]])
print("\n",b)
c=np.array([[3,3,6],[5,4,0],[-1,-2,6]])
print("\n",c)
d=np.array([1,2,3])
print("\n",d)

[[1 2 5 3]
 [2 6 7 8]]

 [[1 5]
 [4 8]
 [9 2]]

 [[ 3  3  6]
 [ 5  4  0]
 [-1 -2  6]]

 [1 2 3]


In [138]:
# horizontal join for the above array is not possibl
vertical=np.vstack((c,d))
print("\n",vertical)
vertical1=np.vstack((d,c))
print("\n",vertical1)



 [[ 3  3  6]
 [ 5  4  0]
 [-1 -2  6]
 [ 1  2  3]]

 [[ 1  2  3]
 [ 3  3  6]
 [ 5  4  0]
 [-1 -2  6]]


In [121]:
concatenation=np.concatenate((b,c),axis=1)
print(concatenation)
concatenation1=np.concatenate((c,b),axis=1)
print("\n",concatenation1)

[[ 1  5  3  3  6]
 [ 4  8  5  4  0]
 [ 9  2 -1 -2  6]]

 [[ 3  3  6  1  5]
 [ 5  4  0  4  8]
 [-1 -2  6  9  2]]


In [120]:
Horizontal=np.hstack((b,c))
print(Horizontal)
Horizontal1=np.hstack((c,b))
print("\n",Horizontal1)

[[ 1  5  3  3  6]
 [ 4  8  5  4  0]
 [ 9  2 -1 -2  6]]

 [[ 3  3  6  1  5]
 [ 5  4  0  4  8]
 [-1 -2  6  9  2]]


In [124]:
arr=np.array([[10,20,30,40,50],[60,70,80,90,95]])
print(arr)
for i in arr:
    for j in i:
        print(j)
        
    

[[10 20 30 40 50]
 [60 70 80 90 95]]
10
20
30
40
50
60
70
80
90
95


In [129]:
for i in np.nditer(arr):
    print(i)


10
20
30
40
50
60
70
80
90
95


In [131]:

for i in arr:
    for j in i:
        print(i)
        

[10 20 30 40 50]
[10 20 30 40 50]
[10 20 30 40 50]
[10 20 30 40 50]
[10 20 30 40 50]
[60 70 80 90 95]
[60 70 80 90 95]
[60 70 80 90 95]
[60 70 80 90 95]
[60 70 80 90 95]


In [132]:
for i in arr:
    print(i)

[10 20 30 40 50]
[60 70 80 90 95]


In [134]:
arr1=np.arange(1,25).reshape(4,6)
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [135]:
#split this into multiple array
np.hsplit(arr1,3)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24]])]

In [136]:
np.vsplit(arr1,4)

[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24]])]

In [139]:
print("\n",a)
print("\n",b)
print("\n",c)


 [[1 2 5 3]
 [2 6 7 8]]

 [[1 5]
 [4 8]
 [9 2]]

 [[ 3  3  6]
 [ 5  4  0]
 [-1 -2  6]]


In [140]:
# append the data
np.append(a,c)

array([ 1,  2,  5,  3,  2,  6,  7,  8,  3,  3,  6,  5,  4,  0, -1, -2,  6])

In [141]:
np.append(a,b)

array([1, 2, 5, 3, 2, 6, 7, 8, 1, 5, 4, 8, 9, 2])

In [145]:
np.append(b,c,axis=1)

array([[ 1,  5,  3,  3,  6],
       [ 4,  8,  5,  4,  0],
       [ 9,  2, -1, -2,  6]])

In [146]:
arr1=np.arange(50,80).reshape(5,6)
arr1

array([[50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61],
       [62, 63, 64, 65, 66, 67],
       [68, 69, 70, 71, 72, 73],
       [74, 75, 76, 77, 78, 79]])

In [153]:
#replace all even number with 1 and odd number with 127
np.where(arr1%2==0,1,127)

array([[  1, 127,   1, 127,   1, 127],
       [  1, 127,   1, 127,   1, 127],
       [  1, 127,   1, 127,   1, 127],
       [  1, 127,   1, 127,   1, 127],
       [  1, 127,   1, 127,   1, 127]])

In [154]:
#if value is greater than 65 then True else false
np.where(arr1>65,True,False)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [156]:
#only even value should be 1 rest is same
np.where(arr1%2==0,1,arr1)

array([[ 1, 51,  1, 53,  1, 55],
       [ 1, 57,  1, 59,  1, 61],
       [ 1, 63,  1, 65,  1, 67],
       [ 1, 69,  1, 71,  1, 73],
       [ 1, 75,  1, 77,  1, 79]])

In [164]:
age=[10,13,30,50,65,70]
arr=np.array(age)
arr


array([10, 13, 30, 50, 65, 70])

In [170]:
#print whose age is greater than 18
arr[arr>18]

array([30, 50, 65, 70])

In [171]:
arr>50

array([False, False, False, False,  True,  True])

In [183]:
(arr>15) & (arr<50)

array([False, False,  True, False, False, False])

In [184]:
(arr>15) | (arr<50)

array([ True,  True,  True,  True,  True,  True])

In [188]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print("\n",a.shape)
#convert this 2d array into 1d
a.flatten()

[[1 2 3]
 [4 5 6]]

 (2, 3)


array([1, 2, 3, 4, 5, 6])

In [189]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [190]:
np.floor(-2.97)

-3.0

In [191]:
np.ceil(-2.97)

-2.0

In [192]:
np.round(-2.97)

-3.0

In [193]:
np.sin(90)

0.8939966636005579

In [194]:
np.cos(90)

-0.4480736161291702

In [195]:
np.tanh(6.8)

0.9999975190129178

In [197]:
np.round(-4.567)

-5.0

In [198]:
# Create two NumPy arrays of the same length with random numerical values. Compute the correlation coefficient between the two arrays
arr1=np.random.randint(1,50,10).reshape(2,5)
arr2=np.random.randint(1,50,10).reshape(2,5)
print(arr1)
print("\n",arr2)
print("\nThe correlation coefficient b/w twoo arrays are: ",np.corrcoef(arr1,arr2))

[[ 3 30  8 28 36]
 [30  4 21 16 28]]

 [[36 28 15 47 20]
 [26 25 49 38 46]]

The correlation coefficient b/w twoo arrays are:  [[ 1.         -0.4025565   0.05115192  0.11780491]
 [-0.4025565   1.         -0.13466643  0.3494499 ]
 [ 0.05115192 -0.13466643  1.         -0.52338602]
 [ 0.11780491  0.3494499  -0.52338602  1.        ]]


In [199]:
# Q2. Create a 2x3 NumPy array with random integers. Multiply each column by a different scalar value without using a loop.
arr3=np.random.randint(1,50,6).reshape(2,3)
print(arr3)
scaler=np.array([2,3,4])
multiply=arr3*scaler
print("\nThe multiplication of different scaller value from the random array is: ",multiply)


[[14 14 36]
 [ 7 33 39]]

The multiplication of different scaller value from the random array is:  [[ 28  42 144]
 [ 14  99 156]]


In [200]:
# create a NumPy array with shape (3, 3) filled with random values. Add a scalar value to each element in the array using broadcasting.
arr4=np.random.rand(3,3)
print(arr4)
scaller_value=7
add=arr4+scaller_value
print("\nThe Added scaller value is: ",add)

[[0.48773507 0.02155288 0.53103012]
 [0.0824912  0.61468575 0.96888686]
 [0.87686535 0.26687516 0.79411011]]

The Added scaller value is:  [[7.48773507 7.02155288 7.53103012]
 [7.0824912  7.61468575 7.96888686]
 [7.87686535 7.26687516 7.79411011]]


In [201]:
#Q3. Create two NumPy arrays with unique integer values. Find the intersection of the two sets using NumPy.
arr5=np.array([1,2,3,4,5,6])
print(arr5)
arr6=np.array([5,6,7,8,9,10])
print("\n",arr6)
print("\nThe intersection of two array is: ",np.intersect1d(arr5,arr6))

[1 2 3 4 5 6]

 [ 5  6  7  8  9 10]

The intersection of two array is:  [5 6]


In [204]:
#UNION
print("\nThe union of two array is: ",np.union1d(arr5,arr6))


The union of two array is:  [ 1  2  3  4  5  6  7  8  9 10]


In [206]:
# Generate two NumPy arrays with integers. Calculate the set difference between the two arrays.
arr7=np.array([1,2,3,4,5,6])
arr8=np.array([5,6,7,8,9,10])
print(arr7)
print("\n",arr8)
print("\nThe set difference between two array is: ",np.setdiff1d(arr7,arr8))
print("\nThe set difference between two array is: ",np.setdiff1d(arr8,arr7))

[1 2 3 4 5 6]

 [ 5  6  7  8  9 10]

The set difference between two array is:  [1 2 3 4]

The set difference between two array is:  [ 7  8  9 10]
